# Generated by Django 5.2.4 on 2025-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
