# Generated by Django 5.2.4 on 2025-07-23 05:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudi', '0003_remove_mediaitem_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
