# Generated by Django 5.2.4 on 2025-07-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudi', '0004_mediaitem_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='video',
        ),
    ]
