# Generated by Django 5.2.4 on 2025-07-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudi', '0005_remove_mediaitem_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
