# Generated by Django 5.2.4 on 2025-07-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudi', '0006_mediaitem_title_mediaitem_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
