# Generated by Django 5.2.4 on 2025-07-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mediaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='image',
        ),
    ]
