# Generated by Django 5.2.4 on 2025-07-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_mediaitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
