# Generated by Django 5.2.4 on 2025-07-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mediaitem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaItem',
        ),
    ]
